### ISSUE TITLE
pip install raincoat-jackett gives ivalid syntax error

### ISSUE THREAD

**Issue by shohart** [Gabisonfire/raincoat#1]
Hello! seems that this is the only project in python than matches my needs, but i can not get it to install ^( 
it gives me an error 

> Collecting raincoat-jackett
>   Downloading https://files.pythonhosted.org/packages/62/e8/c6269b7a4f526a79c3a090e2efc501ce9a3ea77e84b4562a4e999bbd6a05/raincoat-jackett-0.3.tar.gz
>     ERROR: Command errored out with exit status 1:
>      command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lanu23cd/raincoat-jackett/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lanu23cd/raincoat-jackett/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-lanu23cd/raincoat-jackett/pip-egg-info
>          cwd: /tmp/pip-install-lanu23cd/raincoat-jackett/
>     Complete output (6 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-lanu23cd/raincoat-jackett/setup.py", line 13
>         cfg_path = f"{str(Path.home())}/.config/{APP_NAME}.json"
>                                                                ^
>     SyntaxError: invalid syntax
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Gabisonfire** [comment]
Hi @shohart ,

What distro are you trying to install on and what version of python are you using?

I just tried a fresh install from pip on centos7 and python 3.6.8 and it worked.

**Comment by shohart** [comment]
Debian 9.11, and python 3.5.3, i see it seems related to old python in debian repos. but description says that python 3.+ needed (: 
i will proceed with python update then

**Comment by Gabisonfire** [comment]
Also make sure you use pip3 as well!
Let me know if it works, i'll update the requirements

**Comment by Gabisonfire** [comment]
@shohart I'ts because of the f-string, which was added in python 3.6, I'll update the requirements.

**Comment by shohart** [comment]
yeah python 3.7 install fixed it - i can install raincoat and search for torrents. i opened another issue though (:

**Comment by shohart** [comment]
oh i see it is proibably because ascii encoder can not hadnle cyrillic caracters. so it needs to be in utf-8 or smth
