### ISSUE TITLE
ModuleNotFoundError: No module named 'syslog'

### ISSUE THREAD

**Issue by mooseyoose** [Gabisonfire/raincoat#10]
Hey,

When I run raincoat, I get this error:

`\programs\python\python38-32\lib\site-packages\justlog\justlog.py", line 1, in <module>
    import syslog
ModuleNotFoundError: No module named 'syslog'`

Any idea?

**Comment by Gabisonfire** [comment]
I'm guessing you are running from Windows right? Think that I need to change from `syslog` to `logging` from a quick read. I will check a bit later.

**Comment by mooseyoose** [comment]
Windows correct. Thanks

**Comment by Gabisonfire** [comment]
You can use `pip install -U justlog` and it should fix your issue. Tested on Windows.
