### ISSUE TITLE
Automatically choose top result and send to client?

### ISSUE THREAD

**Issue by trip5** [Gabisonfire/raincoat#13]
Hey again.  Version 0.8 looks good.  I can get it working with Qbittorrent at least now in a docker container but could you add one feature for me?  A switch that just grabs the top-seeder result (and exits if no results) would be great because this:

    echo :d 1|raincoat refused_malignant_fire_flac

works fine with torrents that do exist but goes into an endless error loop when there are no results.

**Comment by Gabisonfire** [comment]
Hey, that should be fairly simple to implement, i'll have a look shortly.

**Comment by Gabisonfire** [comment]
You can install from the develop branch using `pip install git+https://github.com/Gabisonfire/raincoat.git@develop` and test the `-d` switch. I tested locally and it worked fine. I'm not going to publish a release yet though as I have other features planned.

**Comment by trip5** [comment]
Sorry it took so long to reply.  The -d switch definitely works... It'll be useful for music for sure but movies, not so much due to XXX parodies showing up as the top seeded.  Lol.

I'm still having trouble getting Deluge to work but that may be a quirk since I'm using an older Deluge in my Docker (1.3.15 was the last one to function with the Windows UI client).  I can't get Transmission to work either.  No problems using a modern Qbittorrent.

I'm also having trouble getting local download to work.  I don't know enough about Libtorrent or Python but I seem to understand Libtorrent is a hacky solution and it isn't always easy to make it work with Python.  I tried various pre-made pre-compiled docker containers as bases but no joy yet.  So I can ask what your Linux build and python version is?  I might have more success if I have a base something like yours...  And this would make a wonderful catch-all solution since all clients have a blackhole watch folder...

**Comment by Gabisonfire** [comment]
> It'll be useful for music for sure but movies, not so much due to XXX parodies showing up as the top seeded.

You can use the `exclude` setting in the config file to eliminate some. 

I tested the local downloads on Manjaro and python 3.7
