### ISSUE TITLE
Discord Bot ( Comptability ) 

### ISSUE THREAD

**Issue by Lucy-2077** [Gabisonfire/raincoat#15]
Hey , I want to open an issue for introducting an way for add raincoat with discord py 
I would make a interactive bot for download on a discord server.
What is possible or if it possible
Good Day !
DefiDegue

**Comment by Gabisonfire** [comment]
I can sure have a look, please provide me with some code on how you'd see this work.

**Comment by Lucy-2077** [comment]
Thanks for the quick answer , Yet i don't have make any codes because im a noob on python specialy on discord py :/

**Comment by Gabisonfire** [comment]
No worries, let me know when you have a better idea of what you need.

**Comment by Lucy-2077** [comment]
Hey , I dont have idea , im a noob lol 
Have you an idea for the discord bot can interact in a session of raincoat , because i cant see how an bot can communicate with raincoat
i would like make exemple : !download <name> and after he select with :d <ID> for download
If you can help me ^^ Thanks :)

**Comment by Gabisonfire** [comment]
Are you looking to write a bot? I can't really help you on that part, there is a lot of information available. Your best bet is to learn how it works and fork this repo and reuse the parts you need.
