### ISSUE TITLE
indexer passed as argument not processed

### ISSUE THREAD

**Issue by MeTimesThree** [Gabisonfire/raincoat#18]
Hi Gab,

thanks for your great tool.
I have a problem with the setting of an indexer on the command line. It seems to be associated with the api key:
    if args.indexer is not None:        
        shared.JACKETT_INDEXER = args.key

In the log it also shows up as None wich seems ok since the (command-line) api key is unset:
[ 2021-05-12 21:30:12.715765 ] :: DBG :: Request made to: http://127.0.0.1:12345/api/v2.0/indexers/None/results?...

Could you maybe take a look at that?

**Comment by Gabisonfire** [comment]
That definitely seems like a typo, thanks for reporting. I've just pushed 1.0, you can update using pip!

**Comment by Gabisonfire** [comment]
Fixed in 1.0

**Comment by MeTimesThree** [comment]
Wow, here i was pondering wether to try to fix it myself or wait a couple of days and then i see you already fixed it and uploaded it to pip.

Works like a charm:
[ 2021-05-12 23:16:41.836721 ] :: DBG :: Request made to: http://127.0.0.1:12345/api/v2.0/indexers/1337x/results?...

Thanks so much fpr this awesome support!
