### ISSUE TITLE
using potato jackett feed results in search in single category - movies

### ISSUE THREAD

**Issue by shohart** [Gabisonfire/raincoat#2]
so, if you try to search via raincoat using a potato feed from jackett config you are limited to a single category: movies, because jacket automatically filters output for  couchpotato in this case... it would be nice to handle rss feed instead

**Comment by takosine** [comment]
I believe this should be as simple as modifying https://github.com/Gabisonfire/raincoat/blob/master/raincoat/raincoat.py#L123 to:

```r = requests.get(f"{JACKETT_URL}?apiKey={APIKEY}&search={search_terms}")```

and using the manual search endpoint in the config instead:

```"jacket_url": "http://localhost:9117/api/v2.0/indexers/all/results"```

As a further optimization, we could just take the root URL as `jacket_url` and allow default to `all` indexers, allowing users to modify this with a `jacket_indexers` config option.

If you'd like, I can test this out locally and submit a PR.

Thank you for creating this tool by the way, it's very close to letting me do what what I've been searching for for a long time!

**Comment by Gabisonfire** [comment]
@takosine I'd sure appreciate that :)

**Comment by takosine** [comment]
I've got a PR all ready, but I think I need permission to submit it :)

**Comment by Gabisonfire** [comment]
@takosine You need to fork, make your change and then you will be able to submit a PR

**Comment by takosine** [comment]
It's been a while, apologies!

**Comment by Gabisonfire** [comment]
Fixed with PR #3 release 0.5 now on pypi
