### ISSUE TITLE
Mass download

### ISSUE THREAD

**Issue by mgaulton** [Gabisonfire/raincoat#20]
Hi There, 
I'd like to be able to specify a search and grab all results to local file, so I can dedupe and then import into client.
Curious if you have a config/switch that would do that?

Thanks.

**Comment by Gabisonfire** [comment]
Hey, there's no option at the moment but that would be fairly easy to implement. I should be able to push a change tomorrow.

**Comment by Gabisonfire** [comment]
Added in [1.1](https://github.com/Gabisonfire/raincoat/releases/tag/1.1)

**Comment by mgaulton** [comment]
Awesome. I really appreciate the effort.
