### ISSUE TITLE
feature request: import from list

### ISSUE THREAD

**Issue by whiteworthy** [Gabisonfire/raincoat#21]
feature that searches and snatches multiple movies/shows from each line in a list file
eg:
raincoat --list list.txt -c config.json -d 3 --local

list would be structured something like this:
breaking bad s01 remux
breaking bad s02 remux
taxi driver remux
etc

**Comment by Gabisonfire** [comment]
Sure, should be simple addition. I'll see if I can implement this tonight or ealry this week.

**Comment by Gabisonfire** [comment]
Feature implemented in 1.2. At the moment, my jackett install is unavailable so I was unable to fully test. Could you install from git and let me know if it works?
`pip install git+https://github.com/Gabisonfire/raincoat.git`

ex: `raincoat --list things_to_search.txt -d`

If it works fine, I'll release to pypi.

Cheers

**Comment by whiteworthy** [comment]
it seems to only search and download the first line on the list, completely ignoring the rest of it.

command used: raincoat --verbose --list list.txt -d -s 'size' -c config.json --local (windows 10)

log/output doesn't seem to have anything useful to it (normal log of single file download)

list looks like this (redacted to avoid tos):
K.X.BluRay.1080p.DD.5.1.x264-O.mp4
R.Z.Y.X.UHD.BluRay.2160p.FLAC.2.0.DV.HEVC.REMUX-grp
A.B.C.1080p.AMZN.WEB-DL.DDP2.0.H.264-grp

**Comment by Gabisonfire** [comment]
Thanks for the feedback. I might have found the issue, please reinstall from git and try again. If it doesn't work, I'll setup a Jackett tomorrow and figure it out.

**Comment by whiteworthy** [comment]
Same issue.

**Comment by Gabisonfire** [comment]
Working in [1.2](https://github.com/Gabisonfire/raincoat/tree/1.2), available on Pypi.
