### ISSUE TITLE
Outdated URLs?

### ISSUE THREAD

**Issue by norey** [Gabisonfire/raincoat#28]
Hello,

I'm currently running Jackett v0.20.2397 and see that the URLs that raincoat use do not match Jackett's.
I can see from the raincoat log that it requests the following:

`http://jackett:9117/api?passkey=<key>&search=string`

While when searching manually in Jackett's UI, the following request is made:

`http://jackett:9117/api/v2.0/indexers/all/results?apikey=<key>&Query=string`

Which is completely different. So I'm just wondering if raincoat is using something else or another version. What am I missing here?

**Comment by Gabisonfire** [comment]
Is the search is still working fine (it is for me on the same jackett version)?
They probably updated their api but still support older paths. I'll have a look and update them.

**Comment by norey** [comment]
No, I'm getting back an error, unless I'm doing something wrong. From the log:

`[ 2022-12-17 11:51:54.018928 ] :: ERR :: The request to Jackett failed. (404) :: http://jackett:9117/api?passkey=<key>&search=naruto`

**Comment by Gabisonfire** [comment]
Can you post your `Raincoat.json` config please? Make sure you redact the api keys and passwords.

**Comment by norey** [comment]
```
{
    "jackett_apikey": "key",
    "jackett_url": "http://jackett:9117/",
    "jackett_indexer": "all",
    "description_length": 100,
    "exclude": "",
    "results_limit": 20,
    "client_url": "",
    "display": "grid",
    "torrent_client": "transmission",
    "torrent_client_username": "",
    "torrent_client_password": "",
    "download_dir": ""
}
```

**Comment by norey** [comment]
Not using a torrent client at the moment, was just testing to see how it works.

**Comment by Gabisonfire** [comment]
Can you try removing the  forward slash at the end of the `jackett_url`

**Comment by norey** [comment]
Yeah, it was like that initially. I had to change it because of this error (no slash after the port number):

`[ 2022-12-17 11:47:47.053102 ] :: ERR :: The request to Jackett failed. (500) :: http://jackett:9117api?passkey=key&search=naruto`

**Comment by Gabisonfire** [comment]
Hmm, that's strange. My config is like so:

```
{
    "jackett_apikey": "my_key",
    "jackett_url": "https://jackett.mydomain.net",
    "jackett_indexer": "all",
    "description_length": 100,
    "exclude": "",
    "results_limit": 20,
    "client_url": "",
    "display": "grid",
    "torrent_client": "transmission",
    "torrent_client_username": "",
    "torrent_client_password": "",
    "download_dir": ""
}
```
And my log yields:
```
[ 2022-12-17 22:00:55.124124 ] :: DBG :: Request made to: https://jackett.domain.net/api/v2.0/indexers/all/results?apikey=key&Query=test
[ 2022-12-17 22:00:55.124482 ] :: DBG :: 200: OK
[ 2022-12-17 22:00:55.124767 ] :: DBG :: Headers: {"User-Agent": "python-requests/2.23.0", "Accept-Encoding": "gzip, deflate", "Accept": "*/*", "Connection": "keep-alive"}
[ 2022-12-17 22:00:55.139409 ] :: DBG :: Search yielded 317 results.
[ 2022-12-17 22:00:55.144947 ] :: DBG :: Search request content: 
```
You are using 1.3.1(or 2) right?

**Comment by norey** [comment]
Weird indeed. I don't know if it matters but I'm running it on macOS 13.0.1.

```
 % pip show raincoat-jackett
Name: raincoat-jackett
Version: 1.3.2
Summary: Raincoat is a tool to search torrents using Jackett and send them to your client.
Home-page: https://github.com/Gabisonfire/raincoat
Author: Gabisonfire
Author-email: gabisonfire@github.com
License:
Location: /usr/local/lib/python3.10/site-packages
Requires: colorama, deluge-client, justlog, python-qbittorrent, requests, tabulate, transmission-clutch
Required-by:
```

**Comment by norey** [comment]
Ok I just tried running it again and it works. Very strange.

```
[ 2022-12-18 15:37:41.805213 ] :: DBG :: Raincoat v1.3.1
[ 2022-12-18 15:37:52.377087 ] :: DBG :: Raincoat v1.3.1
[ 2022-12-18 15:41:18.835544 ] :: DBG :: Raincoat v1.3.1
[ 2022-12-18 15:41:26.531285 ] :: DBG :: Request made to: http://jackett:9117/api/v2.0/indexers/all/results?apikey=key&Query=naruto
[ 2022-12-18 15:41:26.531579 ] :: DBG :: 200: OK
[ 2022-12-18 15:41:26.537998 ] :: DBG :: Headers: {"User-Agent": "python-requests/2.23.0", "Accept-Encoding": "gzip, deflate", "Accept": "*/*", "Connection": "keep-alive"}
[ 2022-12-18 15:41:26.545106 ] :: DBG :: Search yielded 255 results.
```

pip says 1.3.2 and the log says 1.3.1. Probably forgot to update that.
