### ISSUE TITLE
Can't install with pip install raincoat-jackett

### ISSUE THREAD

**Issue by bientavu** [Gabisonfire/raincoat#30]
Hello,

I'm facing an issue while trying to install the raincoat-jackett, i'm using the command `pip install raincoat-jackett`

Here are the logs :
![image](https://github.com/Gabisonfire/raincoat/assets/72080798/5d0e5754-3d8e-4770-9c5d-dfb051c15809)

Note: I'm on Mac M1 ARM
If you could help me on that :)

Thanks!

**Comment by Gabisonfire** [comment]
Thanks for reporting, fixed in https://github.com/Gabisonfire/raincoat/releases/tag/1.3.3
