### ISSUE TITLE
No module named 'justlog'

### ISSUE THREAD

**Issue by bientavu** [Gabisonfire/raincoat#31]
Hello,

After succesfully installed raincoat with your last version, I'm now facing this issue :
![image](https://github.com/Gabisonfire/raincoat/assets/72080798/d7b0c72f-7823-49c6-bd0a-cc83d192f9b3)

Note that I'm not able to locate the configuration file in my home directory :/ anywhere else it could be ?

Thanks!

**Comment by PortalRex** [comment]
Little late but here is the solution. #32

**Comment by PortalRex** [comment]
Also are you sure your config file isn't in /.config?
