### ISSUE TITLE
Dependency version conflict - requests 2.18.4

### ISSUE THREAD

**Issue by btmcsweeney** [Gabisonfire/raincoat#4]
Hi, I ran into an issue when installing this I think you should know about.

There's a dependency conflict between raincoat and the current version of transmission-clutch. raincoat requires requests==2.18.4, transmission-clutch 2.0.3 requires requests<3.0.0,>=2.22.0.

I was able to resolve the issue by specifically installing transmission-clutch 1.0.5, since that was the latest version when you made your last commit, but since the version isn't specified pip installs the latest by default. So I guess the solution would be to either update the version of requests this package requires or require the old version of transmission-clutch.

**Comment by Gabisonfire** [comment]
Thanks for reporting, I'll have a look.

**Comment by Gabisonfire** [comment]
Fixed in https://github.com/Gabisonfire/raincoat/releases/tag/0.7
