### ISSUE TITLE
Using with Elementum (Kodi)

### ISSUE THREAD

**Issue by chicungunya** [Gabisonfire/raincoat#5]
Hello,
Is there anyway to use raincoat with Elementum on Kodi ? https://github.com/elgatito/plugin.video.elementum/

Thanks a lot!

**Comment by Gabisonfire** [comment]
I'll have a look

**Comment by chicungunya** [comment]
> I'll have a look

What do you think finally ? Thanks a lot

**Comment by Gabisonfire** [comment]
Hi,

I did check into it but from what I understand, Elementum does what raincoat does. Raincoat itself is only a convenient way to poke the Jackett API, therefore it would be better suited to add Jackett as an Elementum provider.
