### ISSUE TITLE
trouble adding files to client / new feature: save torrents to folder

### ISSUE THREAD

**Issue by rj-d2** [Gabisonfire/raincoat#6]
Hi, 

i have troubles to add torrents to my clients, i tried deluge and transmission

Deluge log:

[ 2020-05-28 00:00:16.722973 ] :: DBG :: Raincoat v0.7
[ 2020-05-28 00:00:59.409876 ] :: DBG :: Connecting to torrent client...
[ 2020-05-28 00:00:59.410334 ] :: ERR :: Error sending to Deluge. invalid literal for int() with base 10: '//SEEDBOXIP/deluge'

Transmission log:

[ 2020-05-28 00:03:06.733191 ] :: DBG :: Raincoat v0.7
[ 2020-05-28 00:03:13.698561 ] :: DBG :: Connecting to torrent client...
[ 2020-05-28 00:03:13.698675 ] :: DBG :: Transmission connection info: https://SEEDBOXIP, USERNAME
[ 2020-05-28 00:03:13.698858 ] :: DBG :: Adding MOVIENAME 1080p BluRay REMUX AVC FLAC 1 0-EPSiLON with url: None
[ 2020-05-28 00:03:13.698939 ] :: ERR :: Error sending to Transmission. add() got an unexpected keyword argument 'filename'

could you maybe just add an option to save the torrents in a folder instead of adding it to a torrent client?

thx

**Comment by Gabisonfire** [comment]
Seems jackett might not be returning any results. Have you tried with many movies?

`[ 2020-05-28 00:03:13.698858 ] :: DBG :: Adding MOVIENAME 1080p BluRay REMUX AVC FLAC 1 0-EPSiLON with url: None`

Especially this part:
`with url: None`

The issue might not be with your torrent client, but either Jackett or Raincoat not getting a proper torrent url. Either way, it needs to be more verbose and yes, having the option to save the file locally would help with debugging and be a "nice to have". I'll look it up.

**Comment by rj-d2** [comment]
hi, thx for your answer,

i had a mistake in the deluge url, 
raincoat can connect to deluge now, 
but gives the same error as transmission. 

url: None

[ 2020-05-28 10:47:53.456163 ] :: DBG :: Raincoat v0.7
[ 2020-05-28 10:48:01.441905 ] :: DBG :: Connecting to torrent client...
[ 2020-05-28 10:48:01.442263 ] :: DBG :: Deluge connection info: "IP", "PORT", "USERNAME"
[ 2020-05-28 10:48:02.006138 ] :: DBG :: Connected to Deluge
[ 2020-05-28 10:48:02.006500 ] :: DBG :: Adding "TORRENTNAME" with url: None
[ 2020-05-28 10:48:42.196103 ] :: ERR :: Error sending to Deluge. 


i tried it with multiple torrents,
Jackett Version 0.16.554.0

another suggestion would be:
download all found Torrents instead of ID only
raincoat "movie" "all" "location"
download all found torrents to folder

would be great for cross seeding

thx for looking into it,

**Comment by rj-d2** [comment]
could you also pls add the Tracker to the search results
maybe like this:
ID | Description                  | Type   |   Size (GB) |   Seeders |   Leechers |   Ratio |  Tracker|

**Comment by rj-d2** [comment]
hi, sorry if im bugging you but is it working for you?
i get:

```
DBG :: Raincoat v0.7
DBG :: Connecting to torrent client...
DBG :: Deluge connection info: IP, PORT, USER
DBG :: Connected to Deluge
DBG :: Adding TORRENT with url: None
ERR :: Error sending to Deluge. 
```

all the time

**Comment by Gabisonfire** [comment]
I haven't had time to look into this yet, I don't know exactly when I'll be able to. Have you tried poking jackett's api directly to see what kind of response you are getting? Also can you share your config (make sure to redact personnal information)

**Comment by rj-d2** [comment]
hi,

sorry, i dont know anything about api's
this is my config

{
    "jackett_apikey": "API",
    "jackett_url": "https://SEEDBOX/jackett/",
    "jackett_indexer": "all",
    "description_length": 100,
    "exclude": "",
    "results_limit": 20,
    "client_url": "SEEDBOX:PORT",
    "display": "grid",
    "torrent_client": "deluge",
    "torrent_client_username": "USER",
    "torrent_client_password": "PW"
}

**Comment by Gabisonfire** [comment]
try this command and let me know the result:

`curl -L https://{your jacket url}/api/v2.0/indexers/all/results?apikey={your api key} -v`

It should look something like:

`curl -L "http://jackett.mydomain.com/api/v2.0/indexers/all/results?apikey=d8ad9ajsd89ansduans8d7na98snda" -v`

Again, make sure to redact your apikey/domain.

**Comment by rj-d2** [comment]
this seems to work i get a huge list with torrents

output:

`$ curl -L https://{{SEEDBOX}}/jackett/api/v2.0/indexers/all/results?apikey={{API}} -v
*   Trying {{IP}}...
* TCP_NODELAY set
* Connected to {{SEEDBOX}} ({{IP}}) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN={{IP}}
*  start date: May 23 12:43:39 2020 GMT
*  expire date: Aug 21 12:43:39 2020 GMT
*  subjectAltName: host "{{SEEDBOX}}" matched cert's "*.{{IP}}"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> GET /jackett/api/v2.0/indexers/all/results?apikey={{API}} HTTP/1.1
> Host: {{SEEDBOX}}
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx
< Date: Mon, 08 Jun 2020 09:57:38 GMT
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Keep-Alive: timeout=60
< Cache-Control: no-store,no-cache
< Pragma: no-cache
< X-Frame-Options: SAMEORIGIN
< 
{"Results":..........................................................`

**Comment by Gabisonfire** [comment]
Hi,

Sorry for the late reply, I did not receive the notification from your reply. I might have found where the issue is coming from. Would it be possible for you to pm me on Discord? Gabisonfire#1766

**Comment by rj-d2** [comment]
i sent you a friend request
